config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip:[:passwords]
  root to: 'homes#top'
  get 'welcome' => 'homes#welcome', as: 'welcome'

  resource :user, only: [:show, :destroy] do
    collection do
      get 'keyword_new'
      get 'keyword_confirm'
      patch 'keyword_update'
      get 'mission_statement_new'
      get 'mission_statement_confirm'
      patch 'mission_statement_update'
      get 'withdrawal'
    end
  end
  resources :ideals, only: [:index, :destroy] do
    collection do
      get 'personality_new'
      post 'personality_create'
      get 'appearance_new'
      post 'appearance_create'
      get 'lifestyle_new'
      post 'lifestyle_create'
      get 'spend_time_new'
      post 'spend_time_create'
      get 'working_new'
      post 'working_create'
      get 'residence_new'
      post 'residence_create'
      get 'relationship_new'
      post 'relationship_create'
      get 'partner_new'
      post 'partner_create'
      get 'role_model_new'
      post 'role_model_create'
      get 'record'
    end
  end
  resources :problems, except: [:edit, :destroy] do
    collection do
      get 'confirm'
    end
    resources :missions, only: [:create, :destroy] do
      member do
        post 'upload'
      end
      collection do
        post 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :schedules do
    member do
      patch 'all_update'
    end
    resources :plans, only: [:create, :destroy] do
      member do
        patch 'upload'
      end
      collection do
        patch 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :motivations, only: [:index, :destroy] do
    collection do
      get 'positive_new'
      post 'positive_create'
      get 'negative_new'
      post 'negative_create'
      get 'to_do_new'
      post 'to_do_create'
      get 'want_new'
      post 'want_create'
      get 'record'
    end
  end
  resources :scrap_books, except: [:new, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :problem
  has_many :plans, dependent: :destroy

  # 親モデルを保存するときに、Associationで関連づけた子モデルも一緒に保存する
  accepts_nested_attributes_for :plans, allow_destroy: true

  validates :problem_id, presence: true
  validates :title, presence: true

  # context: :create_scheduleをsaveに引数として渡した場合、またはupdateの時のみバリデーションする
	with_options presence: true, on: %i[update create_schedule] do
    validates :start_datetime
    validates :end_datetime
  end

  # context: :create_scheduleをsaveに引数として渡した場合、またはupdateの時のみバリデーションする
  validate :start_end_check, on: %i[update create_schedule]

  #時間の矛盾を防ぐ
  def start_end_check
    if self.start_datetime.present? && self.end_datetime.present?
      errors.add(:end_datetime, "が開始時刻を上回っています。正しく記入してください。") if self.start_datetime > self.end_datetime || self.start_datetime == self.end_datetime
    end
  end

  # 表示形式をランダム表示
  default_scope -> { order(start_datetime: :asc) }
  # 過去のスケジュールを表示
  scope :completion, -> {where('end_datetime <= ?', Time.current)}
  # 日付が未入力のスケジュールを表示
  scope :pending, -> {where(start_datetime: nil, end_datetime: nil)}
  # 未来のスケジュールを表示
  scope :imperfect, -> {where('start_datetime >= ?', Time.current).or(where('start_datetime < ?', Time.current)).and(where('end_datetime > ?', Time.current))}

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_action :not_setting_goals_in_life!

  def new
    @schedule = Schedule.new
    @problems = current_user.problems.activity.order(created_at: :desc)
  end

  def create
    schedule = Schedule.new(schedule_params)
    schedule.user_id = current_user.id
    if schedule.save(context: :create_schedule)
      redirect_to schedule_path(schedule)
    else
      redirect_to new_schedule_path(error: true)
    end
  end

  def index
    @schedules = Schedule.where(user_id: current_user)
  end

  def show
    @plan = Plan.new
    @schedule = Schedule.includes(:plans).find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
    @problems = current_user.problems.activity.order(created_at: :desc)
  end

  def update
    schedule = Schedule.find(params[:id])
    if schedule.update(schedule_params)
      redirect_to schedule_path(schedule.id)
    else
      redirect_to edit_schedule_path(schedule.id, error: true)
    end
  end

  # 複数のplanテーブルを更新する
  def all_update
    schedule = Schedule.find(params[:id])
    schedule.update(schedule_params)
    redirect_to schedule_path(schedule.id)
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy
    redirect_to schedules_path
  end

  private

  # ログインユーザーがmission_statementのカラムと目標を作成していない場合のアクセス制限
  def not_setting_goals_in_life!
    if !current_user.mission_statement.present? || !current_user.problems.present?
      redirect_to welcome_path
    end
  end

  # ストロングパロメータにネストしているPlanモデルをattributesし、スケジュールからplansテーブルの編集を可能にする
  def schedule_params
    params.require(:schedule).permit(:problem_id, :title, :body, :start_datetime, :start_time, :end_datetime, :end_time, plans_attributes: [:id, :priority_status, :progress_status])
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<!--左のページ-->
<div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
  <div>
    <h5 class="smart-frame mb-5">
      <u>
        どの目標に対する予定か<br>
        選んでください
      </u>
    </h5>
  </div>
  <!--スクロール機能-->
  <div class="scroll-radio-buttons">
    <%= f.collection_radio_buttons(:problem_id, problems, :id, :commitment) do |b| %>
      <div class="masking-tape custom-control custom-radio">
        <%= b.radio_button(required: true, class: "custom-control-input") %>
        <%= b.label(class: "custom-control-label") %>
      </div>
    <% end %>
  </div>
</div>

<!--右のページ-->
<div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
  <div class="form-group">
    <%= f.label :title, class: "smart-frame h5" %>
    <%= f.text_field :title, required: true, class: "form-control" %>
  </div>
  <div class="form-group input-group-prepend">
    <%= f.label :start_datetime, class: "input-group-text" %>
    <%= f.datetime_field :start_datetime, required: true, class: 'form-control' %>
  </div>
  <div class="form-group input-group-prepend">
    <%= f.label :end_datetime, class: "input-group-text" %>
    <%= f.datetime_field :end_datetime, required: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "smart-frame h5" %>
    <%= f.text_area :body,rows: "3", class: "form-control" %>
  </div>
  <div>
    <%= f.submit "登録", class: "btn btn-outline-primary px-5" %>
  </div>
</div>

app/views/schedules/_left_error.html.erb
<div class="cross-frame">
  <p>
    終了時間は開始時間より<br>
    過去にならないように<br>
    注意してください
  </p>
  <p>
    予定の作成が終わった後は<br>
    その予定に関するToDoリストを<br>
    作っていくことになります
  </p>
</div>

app/views/schedules/_right_error.html.erb
<p>
  その後にToDoリストを<br>
  作成していくことになります<br>
  ToDoリストを完遂していくことで<br>
  一歩ずつ目標の達成に近づいていきます
</p>
<p>
  ToDoリストは<br>
  目標を達成するための課題となる予定を<br>
  さらに細かくした課題となります
</p>
<p>
  全ての行動と全ての考えが<br>
  あなたの理想を叶える力になります
</p>

app/views/schedules/edit.html.erb
<div class="container-fluid">
  <% if params[:error] %>

    <!--予定編集に失敗した場合のエラー文-->
    <div class="row justify-content-center open-book my-5 py-3">
      <!--左のページ-->
      <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
        <h5 class="smart-frame bg-warning">
          <u>
            予定の編集に失敗しました
          </u>
        </h5>
        <%= render 'left_error' %>
      </div>

      <!--右のページ-->
      <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
        <%= render 'right_error' %>
        <div class="d-flex justify-content-around">
          <%= link_to "もう一度予定を編集する", edit_schedule_path(@schedule), class: "btn btn-secondary" %>
          <%= link_to "カレンダーに戻る", schedules_path, class: "btn btn-info" %>
        </div>
      </div>
    </div>

  <% else %>

    <!--予定の編集フォーム-->
    <%= form_with model: @schedule, url: schedule_path(@schedule), method: :patch, class: "row justify-content-center open-book my-5 py-3" do |f| %>
      <%= render :partial =>'form', :locals => { :f => f, problems: @problems } %>
    <% end %>

  <% end %>
</div>

app/views/schedules/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 p-5">
    <div id='calendar' class="m-5 p-5 bg-light">
      <%= link_to "予定を立てる", new_schedule_path, class: "btn btn-block btn-outline-primary" %>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="container-fluid">
  <% if params[:error] %>

    <!--予定作成に失敗した場合のエラー文-->
    <div class="row justify-content-center open-book my-5 py-3">

      <!--左のページ-->
      <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
        <h5 class="smart-frame bg-warning">
          <u>
            予定の作成に失敗しました
          </u>
        </h5>
        <%= render 'left_error' %>
      </div>

      <!--右のページ-->
      <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
        <%= render 'right_error' %>
        <div class="d-flex justify-content-around">
          <%= link_to "もう一度予定を作成する", new_schedule_path, class: "btn btn-primary" %>
          <%= link_to "カレンダーに戻る", schedules_path, class: "btn btn-info" %>
        </div>
      </div>
    </div>

  <% else %>

    <%= form_with model: @schedule,url: schedules_path, method: :post, class: "row justify-content-center open-book my-5 py-3" do |f| %>
      <%= render :partial =>'form', :locals => { :f => f, problems: @problems } %>
    <% end %>

  <% end %>
</div>

app/views/schedules/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column">
      <h5 class="smart-frame">
        <u>
          <% if @schedule.problem.progress_status == "finish" %>
            達成した目標の予定詳細
          <% elsif @schedule.problem.progress_status == "pending" %>
            保留にした目標の予定詳細
          <% else %>
            進行中の目標の予定詳細
          <% end %>
        </u>
      </h5>
      <div class="card">
        <%= link_to problem_path(@schedule.problem_id), class: "btn btn-block btn-link card-header" do %>
          <%= @schedule.problem.commitment %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= @schedule.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted">
            <%= @schedule.start_datetime.strftime("%Y年%-m月%-d日%-H時%M分") %><br>
            〜<br>
            <%= @schedule.end_datetime.strftime("%Y年%-m月%-d日%-H時%M分") %>
          </h6>
          <p class="card-text">
            <%= safe_join(@schedule.body.split("\n"),tag(:br)) %>
          </p>
        </div>
      </div>

      <% if @schedule.plans.programme.present? %>

        <!--予定のタスクが稼働状態になっている場合-->
        <!--タブ表示機能-->
        <nav>
          <div class="nav nav-tabs strip-paper" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active btn btn-outline-primary" id="nav-programme-tab" data-toggle="tab" href="#nav-programme" role="tab" aria-controls="nav-programme" aria-selected="true">全てのリスト</a>
            <a class="nav-item nav-link btn btn-outline-success" id="nav-emergency-tab" data-toggle="tab" href="#nav-emergency" role="tab" aria-controls="nav-emergency" aria-selected="false">大事なこと</a>
            <a class="nav-item nav-link btn btn-outline-info" id="nav-important-tab" data-toggle="tab" href="#nav-important" role="tab" aria-controls="nav-important" aria-selected="false">重要なこと</a>
            <a class="nav-item nav-link btn btn-outline-warning" id="nav-interruption-tab" data-toggle="tab" href="#nav-interruption" role="tab" aria-controls="nav-interruption" aria-selected="false">やるべきこと</a>
            <a class="nav-item nav-link btn btn-outline-danger" id="nav-eliminate-tab" data-toggle="tab" href="#nav-eliminate" role="tab" aria-controls="nav-eliminate" aria-selected="false">辞めること</a>
            <a class="nav-item nav-link disabled btn btn-secondary">リスト件数：<%= @schedule.plans.programme.count %>件</a>
          </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">

          <!--全て表示するタブ-->
          <div class="tab-pane fade show active" id="nav-programme" role="tabpanel" aria-labelledby="nav-programme-tab">
            <%= form_with model: @schedule, url: all_update_schedule_path(@schedule.id), method: :patch do |f| %>
              <h5 class="smart-frame">
                <u>
                  全てのToDoリスト
                </u>
              </h5>
              <div class="cross-frame font-weight-bold">
                <p>
                  <u>優先順位と進捗状況</u>を変更して管理<br>
                  全てのタスクが完了になるよう<br>
                  努めてください
                </p>
                <!--スクロール機能-->
                <div class="scroll-box">
                  <ul class="list-group list-group-flush">
                    <%= f.fields_for :plans, @schedule.plans.programme do |af| %>
                      <li class="list-group-item">
                        <div class="row">
                          <div class="col align-self-center">
                            <%= af.text_field :challenge, disabled: true, class: "form-control" %>
                            <%= af.select :priority_status, Plan.priority_statuses.keys.map {|k| [I18n.t("enums.plan.priority_status.#{k}"), k]}, class: "form-control badge badge-info badge-pill strip-text" %>
                          </div>
                          <div class="col">
                            <div class="form-group mb-0">
                              <%= af.radio_button :progress_status, Plan.progress_statuses.key(0), class: "form-check-input" %>
                              <%= af.label :progress_status_unstarted, Plan.progress_statuses_i18n[:unstarted], class: "form-check-label" %>
                            </div>
                            <div class="form-group mb-0">
                              <%= af.radio_button :progress_status, Plan.progress_statuses.key(1), class: "form-check-input" %>
                              <%= af.label :progress_status_finish, Plan.progress_statuses_i18n[:finish], class: "form-check-label" %>
                            </div>
                            <div class="form-group mb-0">
                              <%= af.radio_button :progress_status, Plan.progress_statuses.key(2), class: "form-check-input" %>
                              <%= af.label :progress_status_process, Plan.progress_statuses_i18n[:process], class: "form-check-label" %>
                            </div>
                            <div class="form-group mb-0">
                              <%= af.radio_button :progress_status, Plan.progress_statuses.key(3), class: "form-check-input" %>
                              <%= af.label :progress_status_postpone, Plan.progress_statuses_i18n[:postpone], class: "form-check-label" %>
                            </div>
                            <div class="form-group mb-0">
                              <%= af.radio_button :progress_status, Plan.progress_statuses.key(4), class: "form-check-input" %>
                              <%= af.label :progress_status_withdraw, Plan.progress_statuses_i18n[:withdraw], class: "form-check-label" %>
                            </div>
                          </div>
                        </div>
                      </li>
                    <% end %>
                  </ul>
                </div>
                <%= f.submit "更新する", class: "btn btn-success my-3" %>
              </div>
            <% end %>
          </div>

          <!--大事なことのタブ-->
          <div class="tab-pane fade" id="nav-emergency" role="tabpanel" aria-labelledby="nav-emergency-tab">
            <h5 class="smart-frame">
              <u>
                大事なこと件数：<%= @schedule.plans.emergency.count %>
              </u>
            </h5>
            <div class="cross-frame font-weight-bold">
              <p>
                <u>大事なこと</u><br>
                必須のタスク<br>
                必ず実行しないといけない活動
              </p>
              <!--スクロール機能-->
              <div class="scroll-box">
                <ul class="list-group">
                  <% @schedule.plans.emergency.each do |emergency| %>
                    <li class="list-group-item d-flex align-items-center">
                      <%= emergency.challenge %>
                      <span class="badge badge-success badge-pill strip-text ml-auto mr-3"><%= emergency.progress_status_i18n %></span>
                      <%= link_to "削除する", schedule_plan_path(@schedule, emergency.id), method: :delete, class: "strip-text badge badge-danger badge-pill" %>
                    </li>
                   <% end %>
                </ul>
              </div>
            </div>
          </div>

          <!--重要なことのタブ-->
          <div class="tab-pane fade" id="nav-important" role="tabpanel" aria-labelledby="nav-important-tab">
            <h5 class="smart-frame">
              <u>
                重要なこと件数：<%= @schedule.plans.important.count %>
              </u>
            </h5>
            <div class="cross-frame font-weight-bold">
              <p>
                <u>重要なこと</u><br>
                生産性、効果性のタスク<br>
                大事なことタスクを減らす活動
              </p>
              <div class="scroll-box">
                <ul class="list-group">
                  <% @schedule.plans.important.each do |important| %>
                    <li class="list-group-item d-flex align-items-center">
                      <%= important.challenge %>
                      <span class="badge badge-info badge-pill strip-text ml-auto mr-3"><%= important.progress_status_i18n %></span>
                      <%= link_to "削除する", schedule_plan_path(@schedule, important.id), method: :delete, class: "strip-text badge badge-danger badge-pill" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

          <!--やるべきことのタブ-->
          <div class="tab-pane fade" id="nav-interruption" role="tabpanel" aria-labelledby="nav-interruption-tab">
            <h5 class="smart-frame">
              <u>
                やるべきこと件数：<%= @schedule.plans.interruption.count %>
              </u>
            </h5>
            <div class="cross-frame font-weight-bold">
              <p>
                <u>やるべきこと</u><br>
                錯覚のタスク<br>
                生産性が上がらないため<br>
                他のタスクが減ることはない
              </p>
              <div class="scroll-box">
                <ul class="list-group">
                  <% @schedule.plans.interruption.each do |interruption| %>
                    <li class="list-group-item d-flex align-items-center">
                      <%= interruption.challenge %>
                      <span class="badge badge-warning badge-pill strip-text ml-auto mr-3"><%= interruption.progress_status_i18n %></span>
                      <%= link_to "削除する", schedule_plan_path(@schedule, interruption.id), method: :delete, class: "strip-text badge badge-danger badge-pill" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

          <!--辞めることのタブ-->
          <div class="tab-pane fade" id="nav-eliminate" role="tabpanel" aria-labelledby="nav-eliminate-tab">
            <h5 class="smart-frame">
              <u>
                辞めること：<%= @schedule.plans.eliminate.count %>
              </u>
            </h5>
            <div class="cross-frame font-weight-bold">
              <p>
                <u>辞めるべきこと</u><br>
                浪費・過剰のタスク<br>
                時間の無駄遣いといえる活動です<br>
                <u>行わないことを大事にしてください</u>
              </p>
              <div class="scroll-box">
                <ul class="list-group list-group-flush">
                  <% @schedule.plans.eliminate.each do |eliminate| %>
                    <li class="list-group-item d-flex align-items-center">
                      <%= eliminate.challenge %>
                      <span class="badge badge-danger badge-pill strip-text ml-auto mr-3"><%= eliminate.progress_status_i18n %></span>
                      <%= link_to "削除する", schedule_plan_path(@schedule, eliminate.id), method: :delete, class: "strip-text badge badge-danger badge-pill" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

        </div>

      <% end %>
      <div class="d-flex justify-content-around my-3">
        <%= link_to "予定を編集", edit_schedule_path(@schedule.id), class: "btn btn-secondary" %>
        <%= link_to "予定を削除", schedule_path(@schedule.id), method: :delete, "data-confirm" =>"削除して本当にいいですか？", class: "btn btn-warning" %>
        <%= link_to "カレンダーへ", schedules_path, class: "btn btn-info" %>
      </div>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column">

      <% if params[:error] %>

      <!--planの作成に失敗した場合-->
        <div class="masking-tape pt-3 m-4">
          <p>
            提案の作成に失敗しました
          </p>
          <p>
            予定を達成するためにするべきことを<br>
            教えてください
          </p>
          <p>
            それは些細なことでも<br>
            簡単なことでも構いません
          </p>
        </div>

      <% else %>

        <!--ページに訪れた際に表示-->
        <h5 class="smart-frame mb-5">
          <u>
            予定を達成するために<br>
            するべきことを教えてください
          </u>
        </h5>

      <% end %>
      <%= form_with model: [@schedule, @plan], url: schedule_plans_path(@schedule.id), method: :post do |f| %>
        <div class="form-inline justify-content-center">
          <%= f.text_field :challenge, class: "form-control" %>
          <%= f.submit "提案する", class: "btn btn-secondary btn-sm" %>
        </div>
      <% end %>
      <% if @schedule.plans.memo.present? %>

        <!--提案が作成されている場合-->
        <h5 class="smart-frame my-4">
          <u>
            提案件数：<%= @schedule.plans.memo.count %>
          </u>
        </h5>
        <div class="cross-frame font-weight-bold">
          <!--スクロール機能-->
          <div class="scroll-page">
            <% @schedule.plans.memo.each do |plan| %>
              <ul class="list-group">
                <li class="list-group-item">
                  <p>
                    <%= plan.challenge %>
                  </p>
                </li>
                <li class="list-group-item d-flex justify-content-around">
                  <%= link_to "リストにする", upload_schedule_plan_path(@schedule, plan), method: :patch, class: "btn btn-outline-success" %>
                  <%= link_to "破棄する", schedule_plan_path(@schedule, plan), method: :delete, class: "btn btn-outline-danger" %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
        <div class="d-flex justify-content-around">
          <%= link_to "全てリストに保存する", bulk_upload_schedule_plans_path(@schedule.id), method: :patch, class: "btn btn-success"  %>
          <%= link_to "全て破棄する", bulk_destroy_schedule_plans_path(@schedule.id), method: :delete, class: "btn btn-danger" %>
        </div>

      <% end %>
    </div>

  </div>
</div>