config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip:[:passwords]
  root to: 'homes#top'
  get 'welcome' => 'homes#welcome', as: 'welcome'

  resource :user, only: [:show, :destroy] do
    collection do
      get 'keyword_new'
      get 'keyword_confirm'
      patch 'keyword_update'
      get 'mission_statement_new'
      get 'mission_statement_confirm'
      patch 'mission_statement_update'
      get 'withdrawal'
    end
  end
  resources :ideals, only: [:index, :destroy] do
    collection do
      get 'personality_new'
      post 'personality_create'
      get 'appearance_new'
      post 'appearance_create'
      get 'lifestyle_new'
      post 'lifestyle_create'
      get 'spend_time_new'
      post 'spend_time_create'
      get 'working_new'
      post 'working_create'
      get 'residence_new'
      post 'residence_create'
      get 'relationship_new'
      post 'relationship_create'
      get 'partner_new'
      post 'partner_create'
      get 'role_model_new'
      post 'role_model_create'
      get 'record'
    end
  end
  resources :problems, except: [:edit, :destroy] do
    collection do
      get 'confirm'
    end
    resources :missions, only: [:create, :destroy] do
      member do
        post 'upload'
      end
      collection do
        post 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :schedules do
    member do
      patch 'all_update'
    end
    resources :plans, only: [:create, :destroy] do
      member do
        patch 'upload'
      end
      collection do
        patch 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :motivations, only: [:index, :destroy] do
    collection do
      get 'positive_new'
      post 'positive_create'
      get 'negative_new'
      post 'negative_create'
      get 'to_do_new'
      post 'to_do_create'
      get 'want_new'
      post 'want_create'
      get 'record'
    end
  end
  resources :scrap_books, except: [:new, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ideal.rb
class Ideal < ApplicationRecord
  belongs_to :user

  enum ideal_status: { personality: 0, appearance: 1, lifestyle: 2, spend_time: 3, working: 4, residence: 5, relationship: 6, partner: 7, role_model: 8 }

  with_options presence: true do
    validates :ideal_status, numericality: { only_integer: true }
    validates :ideal_self
    validates :ideal_detail_self
  end

  # 表示形式をランダム表示
  default_scope -> { order("RANDOM()") }
  # 理想の性格を表示
  scope :personality, -> {where(ideal_status: 0)}
  # 理想の姿を表示
  scope :appearance, -> {where(ideal_status: 1)}
  # 理想の生活を表示
  scope :lifestyle, -> {where(ideal_status: 2)}
  # 理想の時間の使い方を表示
  scope :spend_time, -> {where(ideal_status: 3)}
  # 理想の働き方を表示
  scope :working, -> {where(ideal_status: 4)}
  # 理想の住まいを表示
  scope :residence, -> {where(ideal_status: 5)}
  # 理想の人間関係を表示
  scope :relationship, -> {where(ideal_status: 6)}
  # 理想のパートナーを表示
  scope :partner, -> {where(ideal_status: 7)}
  # 理想のモデルを表示
  scope :role_model, -> {where(ideal_status: 8)}

end

app/controllers/ideals_controller.rb
class IdealsController < ApplicationController

  before_action :not_setting_goals_in_life!
  before_action :ideal_new, only: [:personality_new, :appearance_new, :lifestyle_new, :spend_time_new, :working_new, :residence_new, :relationship_new, :partner_new, :role_model_new]

  def personality_new
  end

  def personality_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 0
    if ideal.save
      redirect_to personality_new_ideals_path(record: true)
    else
      redirect_to personality_new_ideals_path(error: true)
    end
  end

  def appearance_new
  end

  def appearance_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 1
    if ideal.save
      redirect_to appearance_new_ideals_path(record: true)
    else
      redirect_to appearance_new_ideals_path(error: true)
    end
  end

  def lifestyle_new
  end

  def lifestyle_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 2
    if ideal.save
      redirect_to lifestyle_new_ideals_path(record: true)
    else
      redirect_to lifestyle_new_ideals_path(error: true)
    end
  end

  def spend_time_new
  end

  def spend_time_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 3
    if ideal.save
      redirect_to spend_time_new_ideals_path(record: true)
    else
      redirect_to spend_time_new_ideals_path(error: true)
    end
  end

  def working_new
  end

  def working_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 4
    if ideal.save
      redirect_to working_new_ideals_path(record: true)
    else
      redirect_to working_new_ideals_path(error: true)
    end
  end

  def residence_new
  end

  def residence_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 5
    if ideal.save
      redirect_to residence_new_ideals_path(record: true)
    else
      redirect_to residence_new_ideals_path(error: true)
    end
  end

  def relationship_new
  end

  def relationship_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 6
    if ideal.save
      redirect_to relationship_new_ideals_path(record: true)
    else
      redirect_to relationship_new_ideals_path(error: true)
    end
  end

  def partner_new
  end

  def partner_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 7
    if ideal.save
      redirect_to partner_new_ideals_path(record: true)
    else
      redirect_to partner_new_ideals_path(error: true)
    end
  end

  def role_model_new
  end

  def role_model_create
    ideal = Ideal.new(ideal_params)
    ideal.user_id = current_user.id
    ideal.ideal_status = 8
    if ideal.save
      redirect_to role_model_new_ideals_path(record: true)
    else
      redirect_to role_model_new_ideals_path(error: true)
    end
  end

  def index
    @ideals = Ideal.where(user_id: current_user)
  end

  def record
    user_ideal = Ideal.where(user_id: current_user)

    # 理想の性格を確認する場合
    if params[:personality]
      @ideal_name = user_ideal.find_by(ideal_status: 0)
      @ideals = user_ideal.personality.page(params[:page])

    # 理想の姿を確認する場合
    elsif params[:appearance]
      @ideal_name = user_ideal.find_by(ideal_status: 1)
      @ideals = user_ideal.appearance.page(params[:page])

    # 理想のライフスタイルを確認する場合
    elsif params[:lifestyle]
      @ideal_name = user_ideal.find_by(ideal_status: 2)
      @ideals = user_ideal.lifestyle.page(params[:page])

    # 理想の時間の使い方を確認する場合
    elsif params[:spend_time]
      @ideal_name = user_ideal.find_by(ideal_status: 3)
      @ideals = user_ideal.spend_time.page(params[:page])

    # 理想の働き方を確認する場合
    elsif params[:working]
      @ideal_name = user_ideal.find_by(ideal_status: 4)
      @ideals = user_ideal.working.page(params[:page])

    # 理想の住まいを確認する場合
    elsif params[:residence]
      @ideal_name = user_ideal.find_by(ideal_status: 5)
      @ideals = user_ideal.residence.page(params[:page])

    # 理想の人間関係を確認する場合
    elsif params[:relationship]
      @ideal_name = user_ideal.find_by(ideal_status: 6)
      @ideals = user_ideal.relationship.page(params[:page])

    # 理想のパートナーを確認する場合
    elsif params[:partner]
      @ideal_name = user_ideal.find_by(ideal_status: 7)
      @ideals = user_ideal.partner.page(params[:page])

    # 理想のロールモデルを確認する場合
    elsif params[:role_model]
      @ideal_name = user_ideal.find_by(ideal_status: 8)
      @ideals = user_ideal.role_model.page(params[:page])
    end

  end

  def destroy
    ideal = Ideal.find(params[:id])
    ideal.destroy
    redirect_to ideals_path
  end

  private

  def ideal_new
    @ideal = Ideal.new
  end

  # ログインユーザーがmission_statementのカラムと目標を作成していない場合のアクセス制限
  def not_setting_goals_in_life!
    if !current_user.mission_statement.present? || !current_user.problems.present?
      redirect_to welcome_path
    end
  end

  def ideal_params
    params.require(:ideal).permit(:ideal_status, :ideal_self, :ideal_detail_self)
  end

end

app/helpers/ideals_helper.rb
module IdealsHelper
end

app/views/ideals/_form.html.erb
<div class="form-group">
  <%= f.label :ideal_self, class: "font-weight-bold" %><br/>
  <%= f.text_field :ideal_self, autofocus: true, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :ideal_detail_self, class: "font-weight-bold" %><br/>
  <%= f.text_area :ideal_detail_self, rows: "3", autofocus: true, class: "form-control" %>
</div>
<div class="d-flex justify-content-around">
  <%= f.submit '記録する', class: "btn btn-outline-primary" %>
  <%= link_to "一覧画面に戻る", ideals_path, class: "btn btn-outline-info" %>
</div>

app/views/ideals/appearance_new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <!--タブ表示機能-->
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <a class="nav-item nav-link active" id="nav-appearance-tab" data-toggle="tab" href="#nav-appearance" role="tab" aria-controls="nav-appearance" aria-selected="true">理想の姿</a>
          <a class="nav-item nav-link " id="nav-keyword-tab" data-toggle="tab" href="#nav-keyword" role="tab" aria-controls="nav-keyword" aria-selected="false">キーワード</a>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">

        <!--理想の姿のタブ-->
        <div class="tab-pane fade show active" id="nav-appearance" role="tabpanel" aria-labelledby="nav-appearance-tab">
          <div class="smart-content text-center font-weight-bold mt-0">
            <% if params[:error] %>

              <!--バリデーションエラーが発生した場合-->
              <h5 class="smart-frame bg-warning">
                <u>
                  理想の姿の作成に<br>
                  失敗しました
                </u>
              </h5>
              <p>
                教えていただいた理想の姿に<br>
                空欄があったみたいです
              </p>
              <p>
                おしゃれというのは<br>
                考え方や行動が変わります<br>
                そして気分や気持ちも変わります
              </p>
              <p>
                理想の姿に近づけていく<br>
                それはあなたにとっての<br>
                全ての原動力の一つとなります
              </p>
              <p>
                価値が高くなくていいんです<br>
                あなたが身に纏うことで<br>
                それは誰にとっても<br>
                価値の高いものになります
              </p>

            <% else %>

              <!--ページに訪れた際に表示-->
              <p class="mt-1">
                あなたが思い描く将来の姿には<br>
                あなた自身がいることと思います
              </p>
              <p>
                どんな表情をしていますか<br>
                髪の長さやセットは<br>
                どのようなものですか
              </p>
              <p>
                メイクはどのようなメイクですか<br>
              </p>
              <p>
                体型は標準ですか<br>
                それともモデル体型<br>
                もしくは筋肉質ですか
              </p>
              <p>
                持っている服装や<br>
                着ている服装<br>
                アクセサリーはしていますか
              </p>
              <p>
                思い描く未来の<br>
                想像する未来の<br>
                あなたの姿を教えて下さい
              </p>

            <% end %>
          </div>
        </div>

        <!--キーワードのタブ-->
        <div class="tab-pane fade" id="nav-keyword" role="tabpanel" aria-labelledby="nav-keyword-tab">
          <%= render 'users/keyword_show' %>
        </div>
      </div>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <% if params[:record] %>

        <!--保存に成功した場合-->
        <h5 class="masking-tape">
          <u>
            理想の姿を記録しました
          </u>
        </h5>

      <% else %>

        <!--ページに訪れた際に表示-->
        <h5 class="smart-frame">
          <u>
            あなたが思い描く<br>
            理想の姿を教えて下さい
          </u>
        </h5>

      <% end %>
      <p>
        ヘアスタイルやメイク<br>
        体型<br>
        ファッション<br>
        ひとつずつで構いません
      </p>
      <p>
        あなたの中にあるイメージをそのまま教えて下さい<br>
      </p>
      <p>
        すでに体現している人がいるなら<br>
        その人も教えて下さい
      </p>
      <%= form_with model: @ideal, url: appearance_create_ideals_path, method: :post do |f| %>
        <%= render :partial =>'form', :locals => {:f => f}  %>
      <% end %>
    </div>

  </div>
</div>

app/views/ideals/confirm.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-4">

    <!--左のページ-->
    <div class="left-page col text-center m-5 p-5">
      <p>
        あなたにとっての理想の将来を<br>
        教えていただきました
      </p>
      <p>
        最初に書いていただきました<br>
        理想はあなたの<br>
        生涯をかけた目標<br>
        これから叶えていくための目標
      </p>
      <p>
        それらを叶え続けるために必要な<br>
        モチベーションであり<br>
        思い続けてイメージし続けることによって<br>
        現実にとって変わる<br>
        これから得ていくものになります
      </p>
      <p>
        叶えたい理想であり<br>
        イメージできる理想である<br>
        ということを改めて確認してください
      </p>
      <p>
        これから教えていただきたいこと
      </p>
      <p>
        あなたの人生において
        どんなことより大切にしていることです
      </p>
      <p>
        大切にしていることだとしても
        あなた自身が気づいていないことも
      </p>
      <p>
        それをこの本に問いかけることによって
        大切にしていたことを知ることができます
      </p>
    </div>

    <!--右のページ-->
    <div class="right-page col text-center m-5 p-5">

      <!--理想のテーブルの作成が成功した場合-->
      <% unless params[:error] %>
        <%= render 'show', ideal: @ideal %>
        <div class="d-flex justify-content-around my-3">

          <!--ログインユーザーがミッションステートメントのカラムを持っていない場合-->
          <% if !current_user.mission_statement.present? %>
            <%= link_to "次に進む",new_user_path, class: "btn btn-outline-primary" %>

          <!--ログインユーザーがミッションステートメントのカラムを持っている場合-->
          <% else %>
            <%= link_to "登録する",ideal_path, class: "btn btn-outline-primary" %>

          <% end %>

          <%= link_to "やり直す",ideal_path,method: :delete, class: "btn btn-outline-info" %>
        </div>


      <!--理想のテーブルの作成が失敗した場合-->
      <% else %>
        <h5 class="smart-frame bg-warning">
          <u>
            理想の作成に失敗しました
          </u>
        </h5>
        <p>
          教えていただいた理想の内容に空欄があったみたいです。
        </p>
        <p>
          あなたの理想は案外近くにあるものです<br>
          深く考える必要はありません
        </p>
        <p>
          本当に欲しいものというものは<br>
          普通に過ごしている中で<br>
          ふとした拍子に<br>
          泡のように浮かび上がってくるものです
        </p>
        <div class="d-flex justify-content-around my-3">
          <%= link_to "やり直す",welcome_path, class: "btn btn-outline-info" %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/ideals/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <p>
        あなたにとってのなりたい自分とはなんでしょう
      </p>
      <p>
        思い浮かぶ人がいますか<br>
        思い浮かぶ行動がありますか
      </p>
      <p>
        憧れる立ち振る舞いはありますか<br>
        憧れる生き方はありますか
      </p>
      <p>
        そして逆にこうなりたくない<br>
        これだけはしたくないということはありますか
      </p>
      <p>
        キーワードを基に理想を探してみましょう
      </p>
      <p>
        それはきっとあなたのなかにいるのだから
      </p>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <div class="cross-frame font-weight-bold">
        <%= link_to "人生の指針を閲覧する", user_path, class: "btn btn-block btn-outline-success" %>
        <% if @ideals.present? && @ideals.personality.present? %>

            <!--理想の性格が作成されている場合-->
          <%= link_to "理想の性格を閲覧する", record_ideals_path(personality: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想の性格が作成されていない場合-->
          <%= link_to "理想の性格を想像する", personality_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.appearance.present? %>

            <!--理想の姿が作成されている場合-->
          <%= link_to "理想の姿を閲覧する", record_ideals_path(appearance: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想の姿が作成されていない場合-->
          <%= link_to "理想の姿を想像する", appearance_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.lifestyle.present? %>

            <!--理想のライフスタイルが作成されている場合-->
          <%= link_to "理想のライフスタイルを閲覧する", record_ideals_path(lifestyle: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想のライフスタイルが作成されていない場合-->
          <%= link_to "理想のライフスタイルを想像する", lifestyle_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.spend_time.present? %>

            <!--理想の時間の使い方が作成されている場合-->
          <%= link_to "理想の時間の使い方を閲覧する", record_ideals_path(spend_time: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想の時間の使い方が作成されていない場合-->
          <%= link_to "理想の時間の使い方を想像する", spend_time_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.working.present? %>

            <!--理想の働き方が作成されている場合-->
          <%= link_to "理想の働き方を閲覧する", record_ideals_path(working: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想の働き方が作成されていない場合-->
          <%= link_to "理想の働き方を想像する", working_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.residence.present? %>

            <!--理想の住まいが作成されている場合-->
          <%= link_to "理想の住まいを閲覧する", record_ideals_path(residence: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想の住まいが作成されていない場合-->
          <%= link_to "理想の住まいを想像する", residence_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.relationship.present? %>

            <!--理想の人間関係が作成されている場合-->
          <%= link_to "理想の人間関係を閲覧する", record_ideals_path(relationship: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想の人間関係が作成されていない場合-->
          <%= link_to "理想の人間関係を想像する", relationship_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.partner.present? %>

            <!--理想のパートナーが作成されている場合-->
          <%= link_to "理想のパートナーを閲覧する", record_ideals_path(partner: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想のパートナーが作成されていない場合-->
          <%= link_to "理想のパートナーを想像する", partner_new_ideals_path, class: "btn btn-block btn-outline-primary" %>

        <% end %>
        <% if @ideals.present? && @ideals.role_model.present? %>

            <!--理想のロールモデルが作成されている場合-->
          <%= link_to "理想のロールモデルを閲覧する", record_ideals_path(role_model: true), class: "btn btn-block btn-outline-success" %>

        <% else %>

            <!--理想のロールモデルが作成されていない場合-->
          <%= link_to "理想のロールモデルを想像する", role_model_new_ideals_path, class: "btn btn-block btn-outline-primary"  %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ideals/my.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-4 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 p-5">
      <p>
        あなたにとって<br>
        大事にしていること<br>
        理想の自分の姿
      </p>
      <p>
        何度でも見返して<br>
        まるで現実のように思えるぐらい<br>
        明確に想像してください
      </p>
      <p>
        いつしか<br>
        想像は現実に<br>
        取って代わっていきます
      </p>
      <div class="d-flex justify-content-center my-5 strip-paper">

        <% if @ideals.ideal_status == 0 %>
        <!--理想のステータスが理想の性格の場合-->
          <%= link_to personality_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想の性格を<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 1 %>
        <!--理想のステータスが理想の姿の場合-->
          <%= link_to appearance_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想の姿を<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 2 %>
        <!--理想のステータスがライフスタイルの場合-->
          <%= link_to lifestyle_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想のライフスタイルを<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 3 %>
        <!--理想のステータスが理想の時間の使い方の場合-->
          <%= link_to spend_time_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想の時間の使い方を<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 4 %>
        <!--理想のステータスが理想の働き方の場合-->
          <%= link_to working_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想の働き方を<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 5 %>
        <!--理想のステータスが理想の住まいの場合-->
          <%= link_to residence_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想の住まいを<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 6 %>
        <!--理想のステータスが理想の人間関係の場合-->
          <%= link_to relationship_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想の人間関係を<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 7 %>
        <!--理想のステータスが理想のパートナーの場合-->
          <%= link_to partner_new_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想のパートナーを<br>想像する
          <% end %>

        <% elsif @ideals.ideal_status == 8 %>
        <!--理想のステータスが理想のロールモデルの場合-->
          <%= link_to role_model_ideals_path, class: "list-group-item list-group-item-action list-group-item-primary" do %>
            理想のロールモデルを<br>想像する
          <% end %>

        <% end %>
        <%= link_to "理想の一覧画面に戻る", ideals_path, class: "list-group-item list-group-item-action list-group-item-info" %>
      </div>
    </div>

    <!--右のページ-->
    <div class="right-page col text-center m-5 p-5">
      <h5 class="smart-frame mb-0">
        <u>
          <%= @ideals.ideal_status %>
        </u>
      </h5>
      <div class="cross-frame font-weight-bold mt-0">
        <ul class="list-group list-group-flush scroll-box">
          <% @random_ideals.each do |ideal| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= safe_join(ideal.ideal_self_1.split("\n"),tag(:br)) %>
              <%= link_to "この記録を消す", ideal_path(ideal.id), method: :delete,"data-confirm" =>"この三つの理想の記録を\n本当に消しますか？",  class: "badge badge-danger badge-pill" %>
            </li>
          <% end %>
        </ul>
        <div class="d-flex justify-content-center my-5">
          <%= paginate @random_ideals %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ideals/step10_role_model.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-4 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 p-5">
      <p>
        きっと誰しも思ったことがあるでしょう
      </p>
      <p>
        いいなぁ<br>
        憧れるなぁ
      </p>
      <p>
        それは理想を叶えている姿です
      </p>
      <p>
        理想を体現している人がいるのならば<br>
        あなたがその人のことをよく知って<br>
        その人の行動<br>
        その人の考え方
      </p>
      <p>
       それを真似すればいいだけです
      </p>
      <p>
        何もわからない手探りの状態より<br>
        簡単だと思いませんか
      </p>
      <p>
        まずは話し方からでも<br>
        歩き方でも<br>
        箸の持ち方や<br>
        一つの考え方でも
      </p>
      <p>
        はじめの一歩はなんでもいい<br>
        一歩ずつ歩んでいけばいいのですから
      </p>
      <%= render 'session_keywaord' %>
    </div>


    <!--右のページ-->
    <div class="right-page col text-center m-5 p-5">
      <h5 class="smart-frame">
        <u>
          あなたの理想のパートナー像<br>
          あなたの理想の家族像<br>
          あなたの理想の親友像を<br>
          教えて下さい
        </u>
      </h5>
      <p>
        パートナーは夫婦像とも言えるでしょう<br>
        相棒のような存在ということです
      </p>
      <p>
        あなたにとっての理想はきっと<br>
        理想を想像、妄想<br>
        いっぱい考えていれば
      </p>
      <p>
        その理想はきっと<br>
        あなたの手の届くところに寄ってきます
      </p>
      <%= form_with model: @ideal,url: ideal_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :partner_model %><br />
          <%= f.text_area :partner_model,rows: "3",autofocus: true,class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :family_model %><br />
          <%= f.text_area :family_model,rows: "3",autofocus: true,class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :friend_model %><br />
          <%= f.text_area :friend_model,rows: "3",autofocus: true,class: "form-control" %>
        </div>
        <%= f.submit '次に進む',class: "btn btn-outline-primary" %>
      <% end %>
    </div>

  </div>
</div>