config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip:[:passwords]
  root to: 'homes#top'
  get 'welcome' => 'homes#welcome', as: 'welcome'

  resource :user, only: [:show, :destroy] do
    collection do
      get 'keyword_new'
      get 'keyword_confirm'
      patch 'keyword_update'
      get 'mission_statement_new'
      get 'mission_statement_confirm'
      patch 'mission_statement_update'
      get 'withdrawal'
    end
  end
  resources :ideals, only: [:index, :destroy] do
    collection do
      get 'personality_new'
      post 'personality_create'
      get 'appearance_new'
      post 'appearance_create'
      get 'lifestyle_new'
      post 'lifestyle_create'
      get 'spend_time_new'
      post 'spend_time_create'
      get 'working_new'
      post 'working_create'
      get 'residence_new'
      post 'residence_create'
      get 'relationship_new'
      post 'relationship_create'
      get 'partner_new'
      post 'partner_create'
      get 'role_model_new'
      post 'role_model_create'
      get 'record'
    end
  end
  resources :problems, except: [:edit, :destroy] do
    collection do
      get 'confirm'
    end
    resources :missions, only: [:create, :destroy] do
      member do
        post 'upload'
      end
      collection do
        post 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :schedules do
    member do
      patch 'all_update'
    end
    resources :plans, only: [:create, :destroy] do
      member do
        patch 'upload'
      end
      collection do
        patch 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :motivations, only: [:index, :destroy] do
    collection do
      get 'positive_new'
      post 'positive_create'
      get 'negative_new'
      post 'negative_create'
      get 'to_do_new'
      post 'to_do_create'
      get 'want_new'
      post 'want_create'
      get 'record'
    end
  end
  resources :scrap_books, except: [:new, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/motivation.rb
class Motivation < ApplicationRecord
  belongs_to :user

  enum emotion_status: { positive: 0, negative: 1, to_do: 2, want: 3 }

  with_options presence: true do
    validates :appetite
    validates :memory, uniqueness: { scope: :user }
  end

  # 表示形式をランダム形式
  default_scope -> { order("RANDOM()") }
  # ポジティブモチベーションを表示
  scope :positive, -> {where(emotion_status: 0)}
  # ネガティブモチベーションを表示
  scope :negative, -> {where(emotion_status: 1)}
  # したいことリストを表示
  scope :to_do, -> {where(emotion_status: 2)}
  # ほしい物リストを表示
  scope :want, -> {where(emotion_status: 3)}

end

app/controllers/motivations_controller.rb
class MotivationsController < ApplicationController

  before_action :not_setting_goals_in_life!
  before_action :motivation_new, only: [:positive_new, :negative_new, :to_do_new, :want_new]

  def positive_new
  end

  def positive_create
    motivation = Motivation.new(motivation_params)
    motivation.user_id = current_user.id
    motivation.emotion_status = 0
    if motivation.save
      redirect_to positive_new_motivations_path(record: true)
    else
      redirect_to positive_new_motivations_path(error: true)
    end
  end

  def negative_new
  end

  def negative_create
    motivation = Motivation.new(motivation_params)
    motivation.user_id = current_user.id
    motivation.emotion_status = 1
    if motivation.save
      redirect_to negative_new_motivations_path(record: true)
    else
      redirect_to negative_new_motivations_path(error: true)
    end
  end

  def to_do_new
  end

  def to_do_create
    motivation = Motivation.new(motivation_params)
    motivation.user_id = current_user.id
    motivation.emotion_status = 2
    if motivation.save
      redirect_to to_do_new_motivations_path(record: true)
    else
      redirect_to to_do_new_motivations_path(error: true)
    end
  end

  def want_new
  end

  def want_create
    motivation = Motivation.new(motivation_params)
    motivation.user_id = current_user.id
    motivation.emotion_status = 3
    if motivation.save
      redirect_to want_new_motivations_path(record: true)
    else
      redirect_to want_new_motivations_path(error: true)
    end
  end

  def index
    @motivations = Motivation.where(user_id: current_user)
  end

  def record
    user_motivation = Motivation.where(user_id: current_user)

    # ポジティブモチベーション一覧情報を呼び出す
    if params[:positive]
      @motvations = user_motivation.positive.page(params[:page])

    # ネガティブモチベーション一覧情報を呼び出す
    elsif params[:negative]
      @motvations = user_motivation.negative.page(params[:page])

    # したいことモチベーション一覧情報を呼び出す
    elsif params[:to_do]
      @motvations = user_motivation.to_do.page(params[:page])

    # 欲しいものモチベーション一覧情報を呼び出す
    elsif params[:want]
      @motvations = user_motivation.want.page(params[:page])
    end
  end

  def destroy
    motivation = Motivation.find(params[:id])
    motivation.destroy
    redirect_to motivations_path
  end

  private

  def motivation_new
    @motivation = Motivation.new
  end

  # ログインユーザーがmission_statementのカラムと目標を作成していない場合のアクセス制限
  def not_setting_goals_in_life!
    if !current_user.mission_statement.present? || !current_user.problems.present?
      redirect_to welcome_path
    end
  end

  def motivation_params
    params.require(:motivation).permit(:emotion_status, :appetite, :memory)
  end

end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/views/motivations/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <p>
        ポジティブなことでモチベーションを維持する<br>
        嫌だと思うことでモチベーションを維持する<br>
        将来やりたいことでモチベーションを維持する<br>
        将来ほしい物でモチベーションを維持する
      </p>
      <p>
        モチベーションのスイッチを知ると<br>
        自分が落ち込んだ時や元気が欲しい時<br>
        自分に何をしてあげたらいいのか<br>
        わかるようになります
      </p>
      <p>
        それは自分の気持ちを上げるための<br>
        処方箋のようなものです
      </p>
      <p>
        きっとこれからモチベーションが下がったり<br>
        迷ったりすることがあることでしょう<br>
        ですが何も恐れることはありません
      </p>
      <p>
        たとえ下がったり迷ったとしても<br>
        何度でもモチベーションのスイッチを<br>
        入れることができるからです
      </p>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <% if @motivations.present? %>

        <!--モチベーションテーブルの作成している場合-->
        <h5 class="smart-frame">
          <u>
            あなたのモチベーションのスイッチ
          </u>
        </h5>
        <p>
          自分が落ち込んだ時や元気が欲しい時<br>
          自分に何をしてあげたらいいのか<br>
          自分に何を伝えればいいのか<br>
          わかるようになります
        </p>
        <p>
          それは自分の気持ちを上げるための<br>
          処方箋のようなものです
        </p>
        <p>
          言葉や行動<br>
          考え方や見つめ直すことで<br>
          自分自身のモチベーションスイッチを<br>
          入れてあげてください
        </p>
        <div class="d-flex justify-content-around strip-paper mt-4">
          <% if @motivations.positive.present? %>

            <!--モチベーションテーブルを作成している場合-->
            <%= link_to "ポジティブを閲覧", record_motivations_path(positive: true), class: "btn btn-success" %>

          <% else %>

            <!--モチベーションテーブルを作成していない場合-->
            <%= link_to "ポジティブを記録", positive_new_motivations_path, class: "btn btn-outline-success" %>

          <% end %>
          <% if @motivations.negative.present? %>

            <!--ネガティブテーブルを作成をしている場合-->
            <%= link_to "ネガティブを閲覧", record_motivations_path(negative: true), class: "btn btn-secondary" %>

          <% else %>

            <!--ネガティブテーブルを作成を作成していない場合-->
            <%= link_to "ネガティブを記録", negative_new_motivations_path, class: "btn btn-outline-secondary" %>
          <% end %>
          <% if @motivations.to_do.present? %>

            <!--したいことテーブルを作成を作成している場合-->
            <%= link_to "したいことを閲覧", record_motivations_path(to_do: true), class: "btn btn-primary" %>

          <% else %>

            <!--したいことテーブルを作成を作成していない場合-->
            <%= link_to "したいことを記録", to_do_new_motivations_path, class: "btn btn-outline-primary" %>
          <% end %>
          <% if @motivations.want.present? %>

            <!--欲しいものテーブルを作成を作成している場合-->
            <%= link_to "欲しいものを閲覧", record_motivations_path(want: true), class: "btn btn-warning" %>

          <% else %>

            <!--欲しいものテーブルを作成を作成していない場合-->
            <%= link_to "欲しいものを記録", want_new_motivations_path, class: "btn btn-outline-warning" %>

          <% end %>
        </div>

      <% else %>

        <!--モチベーションテーブルを作成していない場合-->
        <div>
          <p>
            あなたのモチベーションを教えてください
          </p>
          <p>
            あなたの感情が<br>
            ポジティブに動いた瞬間について<br>
            ネガティブに動いた瞬間について<br>
            楽しいものを見つけた瞬間について<br>
            手に入れたいものを見つけた瞬間について
          </p>
          <p>
            心が動いた瞬間<br>
            それがあなたのモチベーションを維持するために<br>
            必要なとても大事な要素であり
          </p>
          <p>
            あなたが<br>
            あなたらしくいられるために<br>
            必要な要素です
          </p>
        </div>
        <div class="d-flex justify-content-around strip-paper mt-4">
          <%= link_to "ポジティブ", positive_new_motivations_path, class: "btn btn-outline-success" %>
          <%= link_to "ネガティブ", negative_new_motivations_path, class: "btn btn-outline-secondary" %>
          <%= link_to "したいこと", to_do_new_motivations_path, class: "btn btn-outline-primary" %>
          <%= link_to "欲しいもの", want_new_motivations_path, class: "btn btn-outline-warning" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/motivations/negative_new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <% if params[:error] %>

        <!--バリデーションエラーが発生した場合-->
        <%= render 'motivations/motivations_template/error' %>

      <% else %>

        <!--このページに訪れた際に表示-->
        <%= render 'motivations/motivations_template/negative' %>

      <% end %>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <% if params[:record] %>

        <!--保存が成功した場合-->
        <h5 class="masking-tape">
          <u>
            ネガティブモチベーションを<br>
            記録しました
          </u>
        </h5>

      <% else %>

        <!--このページに訪れた際に表示-->
        <h5 class="smart-frame">
          <u>
            あなたの感情がネガティブに<br>
            動いた瞬間を教えてください
          </u>
        </h5>

      <% end %>
      <p>
        ネガティブな感情には一般的な定義がなく<br>
        「自分にとって良いか悪いか」<br>
        「人にとって良いか悪いか」<br>
        ただそれだけです
      </p>
      <p>
        そしてこの基準は千差万別です
      </p>
      <p>
        あなたの基準もきっと<br>
        その時置かれている環境や状況<br>
        そして年齢とともに変わっていくでしょう
      </p>
      <%= form_with model: @motivation, url: negative_create_motivations_path, method: :post do |f| %>
        <%= render :partial =>'motivations/motivations_template/form', :locals => {:f => f}  %>
      <% end %>
    </div>

  </div>
</div>

app/views/motivations/own.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-4 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 p-5">

      <% if params[:positive] %>
        <%= render 'motivations/motivations_template/positive' %>
        <div class="d-flex justify-content-around my-3">
          <%= link_to "ポジティブを記録", positive_new_motivations_path, class: "btn btn-outline-success" %>
          <%= link_to "一覧に戻る",motivations_path, class: "btn btn-outline-info" %>
        </div>
      <% elsif params[:negative] %>
        <%= render 'motivations/motivations_template/negative' %>
        <div class="d-flex justify-content-around my-3">
          <%= link_to "ネガティブを記録", negative_new_motivations_path, class: "btn btn-outline-secondary" %>
          <%= link_to "一覧に戻る",motivations_path, class: "btn btn-outline-info" %>

        </div>
      <% elsif params[:to_do] %>
        <%= render 'motivations/motivations_template/to_do' %>
        <div class="d-flex justify-content-around my-3">
          <%= link_to "したいことを記録", to_do_new_motivations_path, class: "btn btn-outline-primary" %>
          <%= link_to "一覧に戻る",motivations_path, class: "btn btn-outline-info" %>

        </div>
      <% elsif params[:want] %>
        <%= render 'motivations/motivations_template/want' %>
        <div class="d-flex justify-content-around my-3">
          <%= link_to "欲しいものを記録", want_new_motivations_path, class: "btn btn-outline-warning" %>
          <%= link_to "一覧に戻る",motivations_path, class: "btn btn-outline-info" %>
        </div>
      <% end %>
    </div>

    <!--右のページ-->
    <div class="right-page col text-center m-5 p-5">
      <div class="scroll-page">
      <% @motvations.each do |motivation| %>
        <div class="cross-frame font-weight-bold">
          <h5 class="my-4">
            <u>
              <%= safe_join(motivation.appetite.split("\n"),tag(:br)) %>
            </u>
          </h5>
          <p>
            <%= safe_join(motivation.memory.split("\n"),tag(:br)) %>
          </p>
          <%= link_to "この記録を消す", motivation_path(motivation.id), method: :delete,"data-confirm" =>"このモチベーションの記録を\n本当に消しますか？",  class: "btn btn-sm btn-danger mb-3" %>
        </div>
      <% end %>
      <div class="d-flex justify-content-center my-5">
        <%= paginate @motvations %>
      </div>
      </div>
    </div>

  </div>
</div>

app/views/motivations/positive_new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <% if params[:error] %>

        <!--バリデーションエラーが発生した場合-->
        <%= render 'motivations/motivations_template/error' %>

      <% else %>

        <!--このページに訪れた際に表示-->
        <%= render 'motivations/motivations_template/positive' %>

      <% end %>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <% if params[:record] %>

        <!--保存が成功した場合-->
        <h5 class="masking-tape">
          <u>
            ポジティブモチベーションを<br>
            記録しました
          </u>
        </h5>

      <% else %>

        <!--このページに訪れた際に表示-->
        <h5 class="smart-frame">
          <u>
            あなたの感情がポジティブに<br>
            動いた瞬間を教えてください
          </u>
        </h5>

      <% end %>
      <p>
        それはあなたが感じたことが全てです。
      </p>
      <p>
        感動して泣きそうになってしまうこと<br>
        音楽を聴いて嬉しくなり楽しくなること<br>
        好きな絵を見てドキドキすること<br>
        言われたら嬉しい言葉<br>
        自分に伝えたい言葉
      </p>
      <p>
        どんなことでも構いません
      </p>
      <p>
        きっとそれは<br>
        ありふれた日常の中にたくさんあります
      </p>
      <%= form_with model: @motivation, url: positive_create_motivations_path, method: :post do |f| %>
        <%= render :partial =>'motivations/motivations_template/form', :locals => {:f => f}  %>
      <% end %>
    </div>

  </div>
</div>

app/views/motivations/record.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">

      <% if params[:positive] %>

        <!--ポジティブモチベーションの一覧表示を閲覧する場合-->
        <%= render 'motivations/motivations_template/positive' %>
        <div class="d-flex justify-content-around">
          <%= link_to "ポジティブを記録", positive_new_motivations_path, class: "btn btn-outline-success" %>
          <%= link_to "一覧に戻る", motivations_path, class: "btn btn-outline-info" %>
        </div>

      <% elsif params[:negative] %>

        <!--ネガティブモチベーションの一覧表示を閲覧する場合-->
        <%= render 'motivations/motivations_template/negative' %>
        <div class="d-flex justify-content-around mt-4">
          <%= link_to "ネガティブを記録", negative_new_motivations_path, class: "btn btn-outline-secondary" %>
          <%= link_to "一覧に戻る", motivations_path, class: "btn btn-outline-info" %>
        </div>

      <% elsif params[:to_do] %>

        <!--したいことモチベーションの一覧表示を閲覧する場合-->
        <%= render 'motivations/motivations_template/to_do' %>
        <div class="d-flex justify-content-around mt-4">
          <%= link_to "したいことを記録", to_do_new_motivations_path, class: "btn btn-outline-primary" %>
          <%= link_to "一覧に戻る", motivations_path, class: "btn btn-outline-info" %>
        </div>

      <% elsif params[:want] %>

        <!--欲しいものモチベーションの一覧表示を閲覧する場合-->
        <%= render 'motivations/motivations_template/want' %>
        <div class="d-flex justify-content-around mt-3">
          <%= link_to "欲しいものを記録", want_new_motivations_path, class: "btn btn-outline-warning" %>
          <%= link_to "一覧に戻る", motivations_path, class: "btn btn-outline-info" %>
        </div>

      <% end %>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <div class="scroll-page">
        <% @motvations.each do |motivation| %>
          <div class="cross-frame font-weight-bold">
            <h5 class="smart-frame">
              <u>
                <%= safe_join(motivation.appetite.split("\n"),tag(:br)) %>
              </u>
            </h5>
            <p>
              <%= safe_join(motivation.memory.split("\n"),tag(:br)) %>
            </p>
            <%= link_to "この記録を消す", motivation_path(motivation.id), method: :delete, "data-confirm" =>"このモチベーションの記録を\n本当に消しますか？", class: "btn btn-sm btn-danger mb-3" %>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-5">
        <%= paginate @motvations %>
      </div>
    </div>

  </div>
</div>

app/views/motivations/to_do_new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <% if params[:error] %>

        <!--バリデーションエラーが発生した場合-->
        <%= render 'motivations/motivations_template/error' %>

      <% else %>

        <!--このページに訪れた際に表示-->
        <%= render 'motivations/motivations_template/to_do' %>

      <% end %>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <% if params[:record] %>

        <!--保存が成功した場合-->
        <h5 class="masking-tape">
          <u>
            してみたいと思うこと<br>
            やってみたいと思うことを<br>
            記録しました
          </u>
        </h5>

      <% else %>

        <!--このページに訪れた際に表示-->
        <h5 class="smart-frame">
          <u>
            してみたいと思うこと<br>
            やってみたいと思うこと<br>
            教えてください
          </u>
        </h5>

      <% end %>
      <p>
        人によっては<br>
        小さいと思えるようなことでも<br>
        できるわけがないと思われるようなことでも
      </p>
      <p>
        なんでも構いません
      </p>
      <p>
        あなたにとって<br>
        それが大切であるのですから
      </p>
      <%= form_with model: @motivation, url: to_do_create_motivations_path, method: :post do |f| %>
        <%= render :partial =>'motivations/motivations_template/form', :locals => {:f => f}  %>
      <% end %>
    </div>

  </div>
</div>

app/views/motivations/want_new.html.erb
<div class="container-fluid">
  <div class="row justify-content-center open-book my-5 py-3">

    <!--左のページ-->
    <div class="left-page col text-center m-5 py-5 pl-5 d-flex flex-column justify-content-center">
      <% if params[:error] %>

        <!--バリデーションエラーが発生した場合-->
        <%= render 'motivations/motivations_template/error' %>

      <% else %>

        <!--このページに訪れた際に表示-->
        <%= render 'motivations/motivations_template/want' %>

      <% end %>
    </div>

    <!--右のページ-->
    <div class="right-page text-center col m-5 py-5 pr-5 d-flex flex-column justify-content-center">
      <% if params[:record] %>

        <!--保存が成功した場合-->
        <h5 class="masking-tape">
          <u>
            欲しいものを記録しました
          </u>
        </h5>

      <% else %>

        <!--このページに訪れた際に表示-->
        <h5 class="smart-frame">
          <u>
            あなたの心が欲しいと思ったもの<br>
            教えてください
          </u>
        </h5>

      <% end %>
      <p>
        手に入れたいもの<br>
        欲しいものの価値は<br>
        自分以外の誰かが決めたものです
      </p>
      <p>
        あなたが欲しいものの価値が低くても<br>
        あなたにとっての価値が高いのであれば
      </p>
      <p>
        それは大きな価値であり<br>
        掛け替えのないものです
      </p>

      <%= form_with model: @motivation, url: want_create_motivations_path, method: :post do |f| %>
        <%= render :partial =>'motivations/motivations_template/form', :locals => {:f => f}  %>
      <% end %>
    </div>

  </div>
</div>