config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip:[:passwords]
  root to: 'homes#top'
  get 'welcome' => 'homes#welcome', as: 'welcome'

  resource :user, only: [:show, :destroy] do
    collection do
      get 'keyword_new'
      get 'keyword_confirm'
      patch 'keyword_update'
      get 'mission_statement_new'
      get 'mission_statement_confirm'
      patch 'mission_statement_update'
      get 'withdrawal'
    end
  end
  resources :ideals, only: [:index, :destroy] do
    collection do
      get 'personality_new'
      post 'personality_create'
      get 'appearance_new'
      post 'appearance_create'
      get 'lifestyle_new'
      post 'lifestyle_create'
      get 'spend_time_new'
      post 'spend_time_create'
      get 'working_new'
      post 'working_create'
      get 'residence_new'
      post 'residence_create'
      get 'relationship_new'
      post 'relationship_create'
      get 'partner_new'
      post 'partner_create'
      get 'role_model_new'
      post 'role_model_create'
      get 'record'
    end
  end
  resources :problems, except: [:edit, :destroy] do
    collection do
      get 'confirm'
    end
    resources :missions, only: [:create, :destroy] do
      member do
        post 'upload'
      end
      collection do
        post 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :schedules do
    member do
      patch 'all_update'
    end
    resources :plans, only: [:create, :destroy] do
      member do
        patch 'upload'
      end
      collection do
        patch 'bulk_upload'
        delete 'bulk_destroy'
      end
    end
  end
  resources :motivations, only: [:index, :destroy] do
    collection do
      get 'positive_new'
      post 'positive_create'
      get 'negative_new'
      post 'negative_create'
      get 'to_do_new'
      post 'to_do_create'
      get 'want_new'
      post 'want_create'
      get 'record'
    end
  end
  resources :scrap_books, except: [:new, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ideal.rb
class Ideal < ApplicationRecord
  belongs_to :user

  enum ideal_status: { personality: 0, appearance: 1, lifestyle: 2, spend_time: 3, working: 4, residence: 5, relationship: 6, partner: 7, role_model: 8 }

  with_options presence: true do
    validates :ideal_status, numericality: { only_integer: true }
    validates :ideal_self
    validates :ideal_detail_self
  end

  # 表示形式をランダム表示
  default_scope -> { order("RANDOM()") }
  # 理想の性格を表示
  scope :personality, -> {where(ideal_status: 0)}
  # 理想の姿を表示
  scope :appearance, -> {where(ideal_status: 1)}
  # 理想の生活を表示
  scope :lifestyle, -> {where(ideal_status: 2)}
  # 理想の時間の使い方を表示
  scope :spend_time, -> {where(ideal_status: 3)}
  # 理想の働き方を表示
  scope :working, -> {where(ideal_status: 4)}
  # 理想の住まいを表示
  scope :residence, -> {where(ideal_status: 5)}
  # 理想の人間関係を表示
  scope :relationship, -> {where(ideal_status: 6)}
  # 理想のパートナーを表示
  scope :partner, -> {where(ideal_status: 7)}
  # 理想のモデルを表示
  scope :role_model, -> {where(ideal_status: 8)}

end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :problem

  validates :memo, presence: true
  
end

app/models/motivation.rb
class Motivation < ApplicationRecord
  belongs_to :user

  enum emotion_status: { positive: 0, negative: 1, to_do: 2, want: 3 }

  with_options presence: true do
    validates :appetite
    validates :memory, uniqueness: { scope: :user }
  end

  # 表示形式をランダム形式
  default_scope -> { order("RANDOM()") }
  # ポジティブモチベーションを表示
  scope :positive, -> {where(emotion_status: 0)}
  # ネガティブモチベーションを表示
  scope :negative, -> {where(emotion_status: 1)}
  # したいことリストを表示
  scope :to_do, -> {where(emotion_status: 2)}
  # ほしい物リストを表示
  scope :want, -> {where(emotion_status: 3)}

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :schedule

  enum priority_status: { emergency: 0, important: 1, interruption: 2, eliminate: 3 }
  enum progress_status: { unstarted: 0, finish: 1, process: 2, postpone: 3, withdraw: 4 }

  validates :challenge, presence: true

  # メモ状態のタスクを表示
  scope :memo, -> {where(programme: "false")}
  # ToDoリストにしたタスクを表示
  scope :programme, -> {where(programme: "true")}
  # ToDoリストにしたステータスが大事なことのタスクを表示
  scope :emergency, -> {where(programme: "true", priority_status: 0)}
  # ToDoリストにしたステータスが重要なことのタスクを表示
  scope :important, -> {where(programme: "true", priority_status: 1)}
  # ToDoリストにしたステータスがやるべきことのタスクを表示
  scope :interruption, -> {where(programme: "true", priority_status: 2)}
  # ToDoリストにしたステータスが辞めることのタスクを表示
  scope :eliminate, -> {where(programme: "true", priority_status: 3)}

end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :user
  has_many :missions, dependent: :destroy
  has_many :schedules, dependent: :destroy

  enum progress_status: { progress: 0, finish: 1, pending: 2 }

  with_options presence: true do
    validates :commitment
    validates :purpose
  end

  # 表示形式がランダム表示
  default_scope -> { order(updated_at: :desc) }
  # 進行中の目標を表示
  scope :activity, -> {where(progress_status: 0)}
  # 完了した目標を表示
  scope :finish, -> {where(progress_status: 1)}
  # 保留した目標を表示
  scope :pending, -> {where(progress_status: 2)}

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :problem
  has_many :plans, dependent: :destroy

  # 親モデルを保存するときに、Associationで関連づけた子モデルも一緒に保存する
  accepts_nested_attributes_for :plans, allow_destroy: true

  validates :problem_id, presence: true
  validates :title, presence: true

  # context: :create_scheduleをsaveに引数として渡した場合、またはupdateの時のみバリデーションする
	with_options presence: true, on: %i[update create_schedule] do
    validates :start_datetime
    validates :end_datetime
  end

  # context: :create_scheduleをsaveに引数として渡した場合、またはupdateの時のみバリデーションする
  validate :start_end_check, on: %i[update create_schedule]

  #時間の矛盾を防ぐ
  def start_end_check
    if self.start_datetime.present? && self.end_datetime.present?
      errors.add(:end_datetime, "が開始時刻を上回っています。正しく記入してください。") if self.start_datetime > self.end_datetime || self.start_datetime == self.end_datetime
    end
  end

  # 表示形式をランダム表示
  default_scope -> { order(start_datetime: :asc) }
  # 過去のスケジュールを表示
  scope :completion, -> {where('end_datetime <= ?', Time.current)}
  # 日付が未入力のスケジュールを表示
  scope :pending, -> {where(start_datetime: nil, end_datetime: nil)}
  # 未来のスケジュールを表示
  scope :imperfect, -> {where('start_datetime >= ?', Time.current).or(where('start_datetime < ?', Time.current)).and(where('end_datetime > ?', Time.current))}

end

app/models/scrap_book.rb
class ScrapBook < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  # 表示形式をランダム表示
  default_scope -> { order("RANDOM()") }

  validates :photo, presence: true

  # 表示する画像のサイズ変更用メソッド
  def get_photo(width,height)
    photo.variant(resize_to_limit: [width,height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :ideal, dependent: :destroy
  has_many :problems, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_many :motivations, dependent: :destroy
  has_many :scrap_books, dependent: :destroy

  validates :planner_name, presence: true

  # keyword_updateの場合のみバリデーションする
  with_options presence: true, on: :keyword_update do
    validates :first_keyword
    validates :second_keyword
    validates :third_keyword
    validates :fourth_keyword
    validates :fifth_keyword
    validates :sixth_keyword
    validates :seventh_keyword
    validates :eighth_keyword
    validates :ninth_keyword
    validates :tenth_keyword
  end

  # mission_statement_updateの場合のみバリデーションする
  with_options presence: true, on: :mission_statement_update do
    validates :mission_statement
    validates :mission_statement_detail
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def welcome
    @problem = current_user.problems
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ideals_helper.rb
module IdealsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/motivations_helper.rb
module MotivationsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/scrap_books_helper.rb
module ScrapBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ce14fd86a0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <div class="background-paper"></div>
    <div class="row no-gutters justify-content-center">

      <% if user_signed_in? && !current_page?(root_path) && !current_page?(withdrawal_user_path) %>
      <!--ユーザーがログインし、ページがトップページじゃない場合のみ表示-->
        <div class ="sidebar text-center col-2 h-100">
          <ul class="list-group list-group-flush">
            <li class="list-group-item list-group-item-action">
              <%= image_tag ('logo.jpg') %>
              <p class="font-weight-bold">"<%= current_user.planner_name %>"</p>

              <% if current_user.mission_statement.present? %>
              <!--ログインユーザーがmission_statementカラムを作成した場合に表示-->
                <p class="font-weight-bold"><%= safe_join(current_user.mission_statement.split("\n"),tag(:br)) %></p>
                <p class="font-weight-bold"><%= safe_join(current_user.mission_statement_detail.split("\n"),tag(:br)) %></p>
              <% end %>
            </li>

            <% if current_user.problems.present? %>
            <!--ログインユーザーがproblemテーブルを作成した時に表示-->
              <%= link_to "カレンダー", schedules_path, class: "list-group-item list-group-item-action list-group-item-info" %>
              <%= link_to "私の目標／課題", problems_path, class: "list-group-item list-group-item-action list-group-item-info" %>
              <%= link_to "私の理想", ideals_path, class: "list-group-item list-group-item-action list-group-item-info" %>
              <%= link_to "スクラップブック", scrap_books_path, class: "list-group-item list-group-item-action list-group-item-info" %>
              <%= link_to "モチベーション", motivations_path, class: "list-group-item list-group-item-action list-group-item-info" %>
            <% end %>

            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action list-group-item-warning" %>
            <%= link_to "退会",withdrawal_user_path, class: "list-group-item list-group-item-action list-group-item-danger" %>
          </ul>
        </div>
      <% end %>

      <main class="col-9">
        <%= yield %>
      </main>
    </div>
  </body>
</html>